tracking:
  persistence:
    existingClaim: temp-data-for-mlflow 
    mountPath: /bitnami/mlflow
    size: 500Mi
  auth:
    enabled: false
  service:
    type: ClusterIP
    ports:
      http: 5000
postgresql:
  enabled: false
  externalDatabase:
    host: airflow-postgresql.airflow.svc.cluster.local
    port: 5432
    existingSecret: airflow-postgresql
    existingSecretPasswordKey: postgres-password
minio:
  enabled: true
  


